name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: code/
          push: false # We'll push in a separate step if the build succeeds
          tags: dewkd98/dewpublic:latest
          platforms: linux/amd64
          load: true # Load the image into the local Docker daemon

      - name: Upload Conda Install Logs
        if: ${{ failure() }} # Only upload if the build failed
        uses: actions/upload-artifact@v3
        with:
          name: conda-install-logs
          path: code/conda_install.log # Path to the log file inside your context

      - name: Push Docker Image
        if: ${{ success() && steps.docker_build.outputs.digest }} # Only push if the build succeeded and digest is available
        uses: docker/build-push-action@v5
        with:
          context: code/
          push: true
          tags: dewkd98/dewpublic:latest
          platforms: linux/amd64
          load: false # No need to load again